#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : criu
Version  : 2.2
Release  : 5
URL      : https://github.com/xemul/criu/archive/v2.2.tar.gz
Source0  : https://github.com/xemul/criu/archive/v2.2.tar.gz
Summary  : RPC library for userspace checkpoint and restore
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: criu-bin
Requires: criu-python
Requires: criu-lib
BuildRequires : asciidoc
BuildRequires : docbook-xml
BuildRequires : libcap-dev
BuildRequires : libnl-dev
BuildRequires : protobuf-bin
BuildRequires : protobuf-c-bin
BuildRequires : protobuf-c-dev
BuildRequires : protobuf-dev
BuildRequires : xmlto-bin
BuildRequires : xmlto-data

%description
## CRIU (Checkpoint and Restore in Userspace)
An utility to checkpoint/restore tasks. Using this tool, you can freeze a
running application (or part of it) and checkpoint it to a hard drive as a
collection of files. You can then use the files to restore and run the
application from the point it was frozen at. The distinctive feature of the CRIU
project is that it is mainly implemented in user space.

%package bin
Summary: bin components for the criu package.
Group: Binaries

%description bin
bin components for the criu package.


%package dev
Summary: dev components for the criu package.
Group: Development
Requires: criu-lib
Requires: criu-bin
Provides: criu-devel

%description dev
dev components for the criu package.


%package lib
Summary: lib components for the criu package.
Group: Libraries

%description lib
lib components for the criu package.


%package python
Summary: python components for the criu package.
Group: Default

%description python
python components for the criu package.


%prep
%setup -q -n criu-2.2

%build
make V=1  %{?_smp_mflags} DESTDIR=$RPM_BUILD_ROOT PREFIX=%{_prefix} LIBDIR=%{_libdir}

%install
rm -rf %{buildroot}
make V=1 install-criu DESTDIR=$RPM_BUILD_ROOT PREFIX=%{_prefix} LIBDIR=%{_libdir}
## make_install_append content
make V=1 install-lib DESTDIR=$RPM_BUILD_ROOT PREFIX=%{_prefix} LIBDIR=%{_libdir}
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/crit
/usr/sbin/criu

%files dev
%defattr(-,root,root,-)
/usr/include/criu/criu-log.h
/usr/include/criu/criu-plugin.h
/usr/include/criu/criu.h
/usr/include/criu/rpc.proto
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
